const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const uid=()=>crypto.randomUUID(); const now=()=>new Date().toISOString();
const app=$('#app'); let state={screen:'auth',tab:'space',space:'work',user:null,data:null,zoom:1,pan:{x:0,y:0},selected:null};
const DB='boonwave-db-v1', STORE='files';
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function putFile(id,file){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(file,id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function getFile(id){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function delFile(id){const db=await openDB();return new Promise((res)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=res})}
const keyUsers='bw_users', keySession='bw_session';
function users(){return JSON.parse(localStorage.getItem(keyUsers)||'{}')} function setUsers(v){localStorage.setItem(keyUsers,JSON.stringify(v))}
function defaultData(){const me=uid();return {version:1,spaces:{personal:{name:'Личное'},work:{name:'Работа'}},nodes:[{id:me,type:'me',space:'personal',title:'Я',subtitle:'Личная система',x:80,y:100,level:2,locked:false,status:'active',priority:'medium',progress:0,tasks:[],contacts:[],attachments:[],notes:'',budget:0,advance:0,balance:0,address:'',due:'',createdAt:now()}],links:[],settings:{lastSpace:'work'},updatedAt:now()}}
function save(){if(!state.user||!state.data)return;const u=users();u[state.user].data=state.data;u[state.user].updatedAt=now();setUsers(u)}
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),1800)}
function icon(type){return ({me:'◎',project:'▣',goal:'◉',idea:'✦',person:'●',stage:'◇',task:'✓'}[type]||'•')}
function typeName(type){return ({me:'Я',project:'Проект',goal:'Цель',idea:'Идея',person:'Человек',stage:'Этап'}[type]||type)}
function boot(){const s=localStorage.getItem(keySession);if(s&&users()[s]){state.user=s;state.data=users()[s].data||defaultData();state.screen='main'}render()}
function render(){app.innerHTML=''; if(state.screen==='auth')return renderAuth(); renderMain()}
function renderAuth(){app.innerHTML=`<div class="auth"><div class="authCard"><div class="brand">BOONWAVE</div><svg class="wave" viewBox="0 0 240 80"><path d="M8 48C62-20 86 100 132 39S190 76 232 18" fill="none" stroke="#d7ff57" stroke-width="7" stroke-linecap="round"/></svg><h1>Личное и работа в одной системе</h1><p>Данные хранятся локально на устройстве. Интернет не нужен после первой загрузки.</p><div class="stack"><div class="field"><label>Email</label><input id="email" type="email" autocomplete="email"></div><div class="field"><label>Пароль</label><input id="pass" type="password" autocomplete="current-password"></div><button class="primary" id="login">Войти</button><button class="secondary" id="register">Создать локальный аккаунт</button></div></div></div>`;
$('#login').onclick=()=>auth(false);$('#register').onclick=()=>auth(true)}
function auth(reg){const e=$('#email').value.trim().toLowerCase(),p=$('#pass').value;if(!e||p.length<4)return toast('Введите email и пароль от 4 символов');const u=users();if(reg){if(u[e])return toast('Аккаунт уже существует');u[e]={password:p,data:defaultData(),createdAt:now()};setUsers(u)}else if(!u[e]||u[e].password!==p)return toast('Неверный email или пароль');state.user=e;state.data=u[e].data;localStorage.setItem(keySession,e);state.screen='main';render()}
function renderMain(){app.innerHTML=`<div class="app"><header class="topbar"><div class="title">BOONWAVE</div><div class="seg"><button data-space="personal" class="${state.space==='personal'?'active':''}">Личное</button><button data-space="work" class="${state.space==='work'?'active':''}">Работа</button></div><button class="iconBtn" id="profile">⋯</button></header><main class="workspace" id="workspace"></main><nav class="bottomNav"><button data-tab="today" class="${state.tab==='today'?'active':''}"><span>◷</span>Сегодня</button><button data-tab="space" class="${state.tab==='space'?'active':''}"><span>⌘</span>Пространство</button><button id="add" class="plus">＋</button><button data-tab="search" class="${state.tab==='search'?'active':''}"><span>⌕</span>Поиск</button><button data-tab="profile" class="${state.tab==='profile'?'active':''}"><span>◎</span>Я</button></nav></div>`;
$$('[data-space]').forEach(b=>b.onclick=()=>{state.space=b.dataset.space;state.tab='space';renderMain()});$$('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;renderMain()});$('#add').onclick=showAdd;$('#profile').onclick=showProfile;
if(state.tab==='space')renderCanvas();if(state.tab==='today')renderToday();if(state.tab==='search')renderSearch();if(state.tab==='profile')renderProfilePage()}
function renderCanvas(){const w=$('#workspace');const nodes=state.data.nodes.filter(n=>n.space===state.space);w.innerHTML=`<div class="canvas" id="canvas"><div class="grid"></div><svg class="links" id="links"></svg></div><div class="fabTools"><button id="zin">＋</button><button id="zout">−</button><button id="fit">⌗</button></div>${nodes.length?'':'<div class="empty"><div><b>Пустое пространство</b>Создайте проект, цель, идею или человека.</div></div>'}`;const c=$('#canvas');applyTransform();nodes.forEach(n=>c.append(nodeEl(n)));drawLinks();$('#zin').onclick=()=>setZoom(state.zoom+.15);$('#zout').onclick=()=>setZoom(state.zoom-.15);$('#fit').onclick=fitView;setupCanvasPan(c)}
function applyTransform(){const c=$('#canvas');if(c)c.style.transform=`translate(${state.pan.x}px,${state.pan.y}px) scale(${state.zoom})`}
function setZoom(z){state.zoom=Math.max(.45,Math.min(1.6,z));autoLevels();applyTransform();renderCanvas()}
function autoLevels(){state.data.nodes.filter(n=>n.space===state.space).forEach(n=>{if(n.manualLevel)return;n.level=state.zoom<.68?1:state.zoom>1.22?3:2});save()}
function fitView(){const ns=state.data.nodes.filter(n=>n.space===state.space);if(!ns.length)return;const minX=Math.min(...ns.map(n=>n.x)),minY=Math.min(...ns.map(n=>n.y)),maxX=Math.max(...ns.map(n=>n.x+300)),maxY=Math.max(...ns.map(n=>n.y+220));const w=$('#workspace');state.zoom=Math.min(1,Math.max(.5,Math.min(w.clientWidth/(maxX-minX+80),w.clientHeight/(maxY-minY+80))));state.pan={x:30-minX*state.zoom,y:30-minY*state.zoom};autoLevels();renderCanvas()}
function setupCanvasPan(c){let start=null;c.addEventListener('pointerdown',e=>{if(e.target.closest('.node'))return;start={x:e.clientX,y:e.clientY,px:state.pan.x,py:state.pan.y};c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!start)return;state.pan={x:start.px+e.clientX-start.x,y:start.py+e.clientY-start.y};applyTransform()});c.addEventListener('pointerup',()=>start=null)}
function nodeEl(n){const el=document.createElement('article');el.className=`node level-${n.level}${n.locked?' locked':''}`;el.style.left=n.x+'px';el.style.top=n.y+'px';el.dataset.id=n.id;const done=n.tasks.filter(t=>t.done).length;const p=n.tasks.length?Math.round(done/n.tasks.length*100):(n.progress||0);el.innerHTML=`<div class="nodeHead"><div class="nodeIcon">${n.cover?'<img data-cover="'+n.cover+'">':icon(n.type)}</div><div class="nodeTitle"><strong>${esc(n.title||typeName(n.type))}</strong><small>${esc(n.subtitle||typeName(n.type))}</small></div><button class="nodeMenu">•••</button></div><div class="nodeBody"><div class="chips mediumOnly"><span class="chip accent">${esc(n.status||'active')}</span><span class="chip">${esc(n.priority||'medium')}</span>${n.due?`<span class="chip">${n.due}</span>`:''}</div><div class="summary mediumOnly"><div class="metric"><span>Прогресс</span><b>${p}%</b></div><div class="metric"><span>Задачи</span><b>${done}/${n.tasks.length}</b></div>${n.type==='project'?`<div class="metric"><span>Бюджет</span><b>${money(n.budget)}</b></div><div class="metric"><span>Остаток</span><b>${money(n.balance)}</b></div>`:''}</div><div class="progress mediumOnly"><i style="width:${p}%"></i></div><div class="section mediumOnly"><h4>Ближайшие задачи</h4>${n.tasks.slice(0,3).map(t=>`<div class="taskRow"><input type="checkbox" data-task="${t.id}" ${t.done?'checked':''}><span>${esc(t.title)}</span></div>`).join('')||'<small>Задач пока нет</small>'}<div class="quickAdd"><input placeholder="Добавить задачу"><button data-quick>＋</button></div></div><div class="fullOnly">${fullNode(n)}</div></div>`;
if(n.cover)loadCover(el,n.cover);el.querySelector('.nodeMenu').onclick=e=>{e.stopPropagation();showNodeMenu(n)};el.querySelector('[data-quick]')?.addEventListener('click',()=>{const inp=el.querySelector('.quickAdd input');if(inp.value.trim()){n.tasks.push({id:uid(),title:inp.value.trim(),done:false,due:''});save();renderCanvas()}});el.querySelectorAll('[data-task]').forEach(ch=>ch.onchange=()=>{n.tasks.find(t=>t.id===ch.dataset.task).done=ch.checked;save();renderCanvas()});el.ondblclick=()=>{n.level=n.level===3?2:3;n.manualLevel=true;save();renderCanvas()};setupDrag(el,n);return el}
function fullNode(n){return `<div class="section"><h4>Описание</h4><div>${esc(n.notes||'Нет описания')}</div></div><div class="section"><h4>Контакты</h4>${n.contacts.slice(0,4).map(c=>`<div class="contactRow"><span>●</span><div><b>${esc(c.name)}</b><small>${esc(c.role||'')}</small></div></div>`).join('')||'<small>Контактов нет</small>'}</div><div class="section"><h4>Вложения</h4>${n.attachments.slice(0,5).map(f=>`<div class="fileRow"><span>${f.kind==='image'?'▧':'▤'}</span><span>${esc(f.name)}</span></div>`).join('')||'<small>Файлов нет</small>'}</div>`}
async function loadCover(el,id){const f=await getFile(id);if(f){const u=URL.createObjectURL(f);const im=el.querySelector('[data-cover]');if(im){im.src=u;im.onload=()=>URL.revokeObjectURL(u)}}}
function setupDrag(el,n){let s=null,timer=null;el.addEventListener('pointerdown',e=>{if(e.target.closest('button,input'))return;timer=setTimeout(()=>showNodeMenu(n),520);if(n.locked)return;s={x:e.clientX,y:e.clientY,nx:n.x,ny:n.y};el.setPointerCapture(e.pointerId)});el.addEventListener('pointermove',e=>{if(!s)return;clearTimeout(timer);n.x=s.nx+(e.clientX-s.x)/state.zoom;n.y=s.ny+(e.clientY-s.y)/state.zoom;el.style.left=n.x+'px';el.style.top=n.y+'px';drawLinks()});el.addEventListener('pointerup',()=>{clearTimeout(timer);if(s){s=null;save()}})}
function drawLinks(){const svg=$('#links');if(!svg)return;svg.innerHTML='';const map=Object.fromEntries(state.data.nodes.map(n=>[n.id,n]));state.data.links.forEach(l=>{const a=map[l.from],b=map[l.to];if(!a||!b||a.space!==state.space||b.space!==state.space)return;const x1=a.x+140,y1=a.y+60,x2=b.x+140,y2=b.y+60,dx=Math.abs(x2-x1)*.45;svg.insertAdjacentHTML('beforeend',`<path d="M${x1},${y1} C${x1+dx},${y1} ${x2-dx},${y2} ${x2},${y2}" fill="none" stroke="rgba(215,255,87,.55)" stroke-width="3" stroke-linecap="round"/>`)})}
function showAdd(){sheet(`<div class="sheetTitle"><h3>Что добавить</h3><button class="ghost" data-close>Закрыть</button></div><div class="sheetGrid">${[['project','▣','Проект'],['goal','◉','Цель'],['idea','✦','Идея'],['person','●','Человек'],['stage','◇','Этап'],['me','◎','Я']].map(x=>`<button class="actionTile" data-type="${x[0]}"><b>${x[1]}</b>${x[2]}</button>`).join('')}</div>`);$$('[data-type]').forEach(b=>b.onclick=()=>showEditor({type:b.dataset.type,space:state.space,x:80+Math.random()*120,y:90+Math.random()*180,level:2,tasks:[],contacts:[],attachments:[]}))}
function showEditor(n){closeOverlay();const isNew=!n.id;modal(`<div class="sheetTitle"><h3>${isNew?'Новый элемент':'Редактирование'}</h3><button class="ghost" data-close>Закрыть</button></div><div class="stack"><div class="row"><div class="field"><label>Название</label><input id="fTitle" value="${escAttr(n.title||'')}"></div><div class="field"><label>Тип</label><select id="fType">${['me','project','goal','idea','person','stage'].map(t=>`<option value="${t}" ${n.type===t?'selected':''}>${typeName(t)}</option>`).join('')}</select></div></div><div class="row"><div class="field"><label>Статус</label><select id="fStatus"><option>подготовка</option><option>в работе</option><option>на паузе</option><option>завершён</option></select></div><div class="field"><label>Приоритет</label><select id="fPriority"><option>высокий</option><option selected>средний</option><option>низкий</option></select></div></div><div class="field"><label>Описание</label><textarea id="fNotes">${esc(n.notes||'')}</textarea></div><div class="row"><div class="field"><label>Срок</label><input id="fDue" type="date" value="${n.due||''}"></div><div class="field"><label>Адрес</label><input id="fAddress" value="${escAttr(n.address||'')}"></div></div><div class="row"><div class="field"><label>Бюджет</label><input id="fBudget" type="number" value="${n.budget||0}"></div><div class="field"><label>Аванс</label><input id="fAdvance" type="number" value="${n.advance||0}"></div></div><button class="primary" id="saveNode">Сохранить</button></div>`);$('#saveNode').onclick=()=>{Object.assign(n,{id:n.id||uid(),title:$('#fTitle').value.trim()||typeName($('#fType').value),type:$('#fType').value,status:$('#fStatus').value,priority:$('#fPriority').value,notes:$('#fNotes').value,due:$('#fDue').value,address:$('#fAddress').value,budget:+$('#fBudget').value||0,advance:+$('#fAdvance').value||0,balance:(+$('#fBudget').value||0)-(+$('#fAdvance').value||0),createdAt:n.createdAt||now()});if(isNew)state.data.nodes.push(n);save();closeOverlay();state.tab='space';renderMain()}}
function showNodeMenu(n){sheet(`<div class="sheetTitle"><h3>${esc(n.title)}</h3><button class="ghost" data-close>Закрыть</button></div><div class="sheetGrid"><button class="actionTile" data-act="edit">✎<span>Редактировать</span></button><button class="actionTile" data-act="level">◫<span>Масштаб</span></button><button class="actionTile" data-act="lock">${n.locked?'🔓':'🔒'}<span>${n.locked?'Открепить':'Зафиксировать'}</span></button><button class="actionTile" data-act="image">▧<span>Изображения</span></button><button class="actionTile" data-act="file">▤<span>Файлы / PDF</span></button><button class="actionTile" data-act="contact">●<span>Контакт</span></button><button class="actionTile" data-act="link">⌁<span>Связать</span></button><button class="actionTile" data-act="delete">×<span>Удалить</span></button></div>`);$$('[data-act]').forEach(b=>b.onclick=()=>nodeAction(b.dataset.act,n))}
function nodeAction(a,n){if(a==='edit')return showEditor(n);if(a==='level'){n.level=n.level%3+1;n.manualLevel=true;save();closeOverlay();renderCanvas()}if(a==='lock'){n.locked=!n.locked;save();closeOverlay();renderCanvas()}if(a==='image'||a==='file'){state.selected=n.id;closeOverlay();const p=a==='image'?$('#imagePicker'):$('#filePicker');p.click()}if(a==='contact')return contactModal(n);if(a==='link')return linkModal(n);if(a==='delete'){state.data.nodes=state.data.nodes.filter(x=>x.id!==n.id);state.data.links=state.data.links.filter(l=>l.from!==n.id&&l.to!==n.id);n.attachments.forEach(f=>delFile(f.id));save();closeOverlay();renderCanvas()}}
function contactModal(n){closeOverlay();modal(`<div class="sheetTitle"><h3>Новый контакт</h3><button class="ghost" data-close>Закрыть</button></div><div class="stack"><input id="cName" placeholder="Имя"><input id="cRole" placeholder="Роль / специализация"><input id="cPhone" placeholder="Телефон"><input id="cEmail" placeholder="Email"><input id="cSocial" placeholder="Instagram / сайт"><button class="primary" id="cSave">Добавить</button></div>`);$('#cSave').onclick=()=>{n.contacts.push({id:uid(),name:$('#cName').value||'Контакт',role:$('#cRole').value,phone:$('#cPhone').value,email:$('#cEmail').value,social:$('#cSocial').value});save();closeOverlay();renderCanvas()}}
function linkModal(n){closeOverlay();const opts=state.data.nodes.filter(x=>x.id!==n.id&&x.space===n.space);modal(`<div class="sheetTitle"><h3>Связать с элементом</h3><button class="ghost" data-close>Закрыть</button></div><div class="stack">${opts.map(x=>`<button class="secondary" data-target="${x.id}">${icon(x.type)} ${esc(x.title)}</button>`).join('')||'Нет других элементов'}</div>`);$$('[data-target]').forEach(b=>b.onclick=()=>{if(!state.data.links.some(l=>(l.from===n.id&&l.to===b.dataset.target)||(l.to===n.id&&l.from===b.dataset.target)))state.data.links.push({id:uid(),from:n.id,to:b.dataset.target});save();closeOverlay();renderCanvas()})}
$('#filePicker').onchange=e=>handleFiles(e.target.files,'file');$('#imagePicker').onchange=e=>handleFiles(e.target.files,'image');
async function handleFiles(list,kind){const n=state.data.nodes.find(x=>x.id===state.selected);if(!n)return;for(const f of list){const id=uid();await putFile(id,f);n.attachments.push({id,name:f.name,size:f.size,type:f.type,kind,createdAt:now()});if(kind==='image'&&!n.cover)n.cover=id}save();toast('Файлы добавлены');renderCanvas();$('#filePicker').value='';$('#imagePicker').value=''}
function renderToday(){const w=$('#workspace'),items=[];state.data.nodes.forEach(n=>n.tasks.forEach(t=>{if(!t.done)items.push({n,t})}));w.innerHTML=`<div class="todayList"><h2>Сегодня</h2>${items.map(({n,t})=>`<div class="todayCard"><b>${esc(t.title)}</b><small>${esc(n.title)} · ${n.space==='work'?'Работа':'Личное'} ${t.due?'· '+t.due:''}</small></div>`).join('')||'<div class="todayCard">Активных задач нет</div>'}</div>`}
function renderSearch(){const w=$('#workspace');w.innerHTML=`<div class="searchList"><h2>Поиск</h2><input id="q" placeholder="Проект, человек, материал, задача..."><div id="results"></div></div>`;$('#q').oninput=e=>{const q=e.target.value.toLowerCase();const ns=state.data.nodes.filter(n=>JSON.stringify(n).toLowerCase().includes(q));$('#results').innerHTML=q?ns.map(n=>`<div class="todayCard"><b>${icon(n.type)} ${esc(n.title)}</b><small>${typeName(n.type)} · ${n.space==='work'?'Работа':'Личное'}</small></div>`).join(''):''}}
function renderProfilePage(){const w=$('#workspace');w.innerHTML=`<div class="todayList"><h2>Профиль и данные</h2><div class="todayCard"><b>${esc(state.user)}</b><small>Локальный аккаунт на этом устройстве</small></div><div class="stack"><button class="secondary" id="export">Экспортировать данные JSON</button><button class="secondary" id="import">Импортировать данные JSON</button><button class="secondary" id="logout">Выйти</button></div></div>`;$('#export').onclick=exportData;$('#import').onclick=()=>$('#importPicker').click();$('#logout').onclick=()=>{localStorage.removeItem(keySession);state={screen:'auth',tab:'space',space:'work',user:null,data:null,zoom:1,pan:{x:0,y:0}};render()}}
$('#importPicker').onchange=async e=>{try{const txt=await e.target.files[0].text(),d=JSON.parse(txt);if(!d.nodes||!d.links)throw 0;state.data=d;save();toast('Данные импортированы');renderMain()}catch{toast('Некорректный файл')}}
function exportData(){const blob=new Blob([JSON.stringify(state.data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`boonwave-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
function showProfile(){sheet(`<div class="sheetTitle"><h3>BOONWAVE</h3><button class="ghost" data-close>Закрыть</button></div><div class="stack"><button class="secondary" id="pExport">Экспорт данных</button><button class="secondary" id="pFit">Вписать пространство</button><button class="secondary" id="pLogout">Выйти</button></div>`);$('#pExport').onclick=exportData;$('#pFit').onclick=()=>{closeOverlay();fitView()};$('#pLogout').onclick=()=>{localStorage.removeItem(keySession);location.reload()}}
function sheet(html){closeOverlay();document.body.insertAdjacentHTML('beforeend',`<div class="sheet overlay"><div class="sheetCard">${html}</div></div>`);$('.overlay').onclick=e=>{if(e.target===e.currentTarget)closeOverlay()};$('[data-close]')?.addEventListener('click',closeOverlay)}
function modal(html){closeOverlay();document.body.insertAdjacentHTML('beforeend',`<div class="modal overlay"><div class="modalCard">${html}</div></div>`);$('.overlay').onclick=e=>{if(e.target===e.currentTarget)closeOverlay()};$('[data-close]')?.addEventListener('click',closeOverlay)}
function closeOverlay(){$('.overlay')?.remove()}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function escAttr(s=''){return esc(s)}function money(v){return new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(v||0)+' ₽'}
if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').then(()=>{let refreshing=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!refreshing){refreshing=true;location.reload()}})})}
setInterval(save,30000);document.addEventListener('visibilitychange',()=>{if(document.hidden)save()});window.addEventListener('beforeunload',save);boot();
