
import {state,clamp} from './state.js';
let viewport,world,nodes,actions;let onChange=()=>{},onOpen=()=>{},onLong=()=>{},onLink=()=>{};
export function initCanvas(handlers){viewport=document.querySelector('#viewport');world=document.querySelector('#world');nodes=document.querySelector('#nodes');actions=document.querySelector('#cardActions');onChange=handlers.onChange;onOpen=handlers.onOpen;onLong=handlers.onLong;onLink=handlers.onLink;viewport.addEventListener('pointerdown',canvasDown,{passive:false});viewport.addEventListener('pointermove',canvasMove,{passive:false});viewport.addEventListener('pointerup',canvasUp,{passive:false});viewport.addEventListener('pointercancel',canvasUp,{passive:false});nodes.addEventListener('pointerdown',nodeDown,{passive:false});nodes.addEventListener('pointermove',nodeMove,{passive:false});nodes.addEventListener('pointerup',nodeUp,{passive:false});nodes.addEventListener('pointercancel',nodeUp,{passive:false});actions.addEventListener('click',actionClick)}
export function applyCamera(){world.style.transform=`translate3d(${state.camera.x}px,${state.camera.y}px,0) scale(${state.camera.scale})`}
function canvasDown(e){if(e.target.closest('.node,.card-actions,.link-hit'))return;e.preventDefault();state.actionsId=null;hideActions();state.selectedId=null;onChange('selection');state.gesture.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});viewport.setPointerCapture?.(e.pointerId);if(state.gesture.pointers.size===1){state.gesture.mode='PAN';state.gesture.start={x:e.clientX,y:e.clientY,cx:state.camera.x,cy:state.camera.y}}else if(state.gesture.pointers.size===2){const p=[...state.gesture.pointers.values()];state.gesture.mode='CANVAS_PINCH';state.gesture.start={dist:d(p[0],p[1]),scale:state.camera.scale,mid:m(p[0],p[1])}}}
function canvasMove(e){if(!state.gesture.pointers.has(e.pointerId))return;e.preventDefault();state.gesture.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(state.gesture.mode==='PAN'&&state.gesture.pointers.size===1){state.camera.x=state.gesture.start.cx+e.clientX-state.gesture.start.x;state.camera.y=state.gesture.start.cy+e.clientY-state.gesture.start.y;applyCamera()}else if(state.gesture.mode==='CANVAS_PINCH'&&state.gesture.pointers.size===2){const p=[...state.gesture.pointers.values()];const ratio=d(p[0],p[1])/state.gesture.start.dist;const next=clamp(state.gesture.start.scale*ratio,.32,1.9);const mid=m(p[0],p[1]);const wx=(state.gesture.start.mid.x-state.camera.x)/state.camera.scale,wy=(state.gesture.start.mid.y-state.camera.y)/state.camera.scale;state.camera.scale=next;state.camera.x=mid.x-wx*next;state.camera.y=mid.y-wy*next;applyCamera()}}
function canvasUp(e){state.gesture.pointers.delete(e.pointerId);if(!state.gesture.pointers.size){state.gesture.mode='IDLE';onChange('camera')}else if(state.gesture.pointers.size===1){const p=[...state.gesture.pointers.values()][0];state.gesture.mode='PAN';state.gesture.start={x:p.x,y:p.y,cx:state.camera.x,cy:state.camera.y}}}
function nodeDown(e){const el=e.target.closest('.node');if(!el)return;e.preventDefault();e.stopPropagation();const id=el.dataset.id,n=state.data.nodes.find(x=>x.id===id);if(!n)return;if(state.linkSourceId&&state.linkSourceId!==id){onLink(id);state.lastTap={id:null,time:0};return}const now=performance.now();if(state.lastTap.id===id&&now-state.lastTap.time<430){state.lastTap={id:null,time:0};state.gesture={mode:'IDLE',pointers:new Map()};onOpen(id);return}state.lastTap={id,time:now};nodes.setPointerCapture?.(e.pointerId);state.gesture.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});state.selectedId=id;state.actionsId=id;onChange('selection');positionActions(n);const timer=setTimeout(()=>{if(state.gesture.mode==='NODE_PENDING')onLong(id)},1200);state.gesture.mode='NODE_PENDING';state.gesture.node={id,startX:e.clientX,startY:e.clientY,x:n.x,y:n.y,moved:false,timer};}
function nodeMove(e){const g=state.gesture;if(!g.node||!g.pointers.has(e.pointerId))return;e.preventDefault();e.stopPropagation();g.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const n=state.data.nodes.find(x=>x.id===g.node.id);if(!n)return;if(g.pointers.size===2){clearTimeout(g.node.timer);const p=[...g.pointers.values()];if(g.mode!=='NODE_PINCH')g.node.pinch={dist:d(p[0],p[1]),level:n.level||2};g.mode='NODE_PINCH';const ratio=d(p[0],p[1])/g.node.pinch.dist;const preview=clamp(ratio,.7,1.35);document.querySelector(`.node[data-id="${n.id}"]`).style.transform=`scale(${preview})`;return}if(g.mode==='NODE_PENDING'||g.mode==='NODE_DRAG'){const dx=(e.clientX-g.node.startX)/state.camera.scale,dy=(e.clientY-g.node.startY)/state.camera.scale;if(Math.hypot(dx,dy)>8){clearTimeout(g.node.timer);g.mode='NODE_DRAG';g.node.moved=true;n.x=g.node.x+dx;n.y=g.node.y+dy;const el=document.querySelector(`.node[data-id="${n.id}"]`);el.style.left=n.x+'px';el.style.top=n.y+'px';positionActions(n);onChange('links')}}}
function nodeUp(e){const g=state.gesture;if(!g.node)return;e.preventDefault();e.stopPropagation();g.pointers.delete(e.pointerId);const n=state.data.nodes.find(x=>x.id===g.node.id);if(g.mode==='NODE_PINCH'&&g.pointers.size===0){const el=document.querySelector(`.node[data-id="${n.id}"]`);const tr=el.style.transform;const scale=parseFloat((tr.match(/scale\(([^)]+)/)||[])[1]||1);n.level=scale>1.12?Math.min(3,(g.node.pinch.level||2)+1):scale<.88?Math.max(1,(g.node.pinch.level||2)-1):(g.node.pinch.level||2);el.style.transform='';clearTimeout(g.node.timer);state.gesture={mode:'IDLE',pointers:new Map()};onChange('node');return}if(g.pointers.size)return;clearTimeout(g.node.timer);const moved=g.node.moved;state.gesture={mode:'IDLE',pointers:new Map()};if(moved)onChange('node')}
function actionClick(e){const b=e.target.closest('button[data-action]');if(!b||!state.actionsId)return;const id=state.actionsId,n=state.data.nodes.find(x=>x.id===id);if(!n)return;if(b.dataset.action==='level'){n.level=(n.level||2)%3+1;onChange('node')}else if(b.dataset.action==='link'){onLink(id)}else if(b.dataset.action==='lock'){n.locked=!n.locked;onChange('node')}positionActions(n)}
export function positionActions(n){if(!actions||!n){hideActions();return}const h={1:120,2:206,3:280}[n.level||2],w={1:180,2:290,3:390}[n.level||2];actions.style.left=`${n.x+w/2-84}px`;actions.style.top=`${n.y+h+12}px`;actions.classList.add('visible')}
export function hideActions(){actions?.classList.remove('visible')}
function d(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function m(a,b){return{x:(a.x+b.x)/2,y:(a.y+b.y)/2}}
