
import {state,uid,TYPE_LABELS,clamp} from './state.js';import * as store from './storage.js';import {putFile,getUrl} from './media.js';import {appTemplate,authTemplate,shellTemplate,nodeHtml,hydrateCovers,detailHtml,editorHtml,createPicker} from './render.js';import {initCanvas,applyCamera,positionActions,hideActions} from './canvas.js';import {renderLinks,startLink} from './links.js';
const app=document.querySelector('#app');app.innerHTML=appTemplate();const auth=document.querySelector('#auth'),shell=document.querySelector('#shell'),notice=document.querySelector('#notice');let pendingMedia=null;
boot();
function boot(){const s=store.getSession();if(s){state.userId=s;state.data=store.load(s);showShell()}else showAuth();setTimeout(()=>document.querySelector('#splash')?.classList.add('hide'),650);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
function showAuth(){shell.classList.add('hidden');auth.classList.remove('hidden');auth.innerHTML=authTemplate();auth.querySelectorAll('[data-auth]').forEach(b=>b.onclick=()=>{state.ui.authMode=b.dataset.auth;showAuth()});auth.querySelector('#authForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),email=f.get('email').trim(),pw=f.get('password');try{const id=state.ui.authMode==='login'?store.login(email,pw):store.register(email,pw);store.setSession(id);state.userId=id;state.data=store.load(id);showShell()}catch(err){toast(err.message)}};auth.querySelector('#demoEnter').onclick=()=>{const id='visual-demo';store.setSession(id);state.userId=id;state.data=store.load(id);if(!state.data.nodes.length)state.data=demo();showShell()}}
function showShell(){auth.classList.add('hidden');shell.classList.remove('hidden');shell.innerHTML=shellTemplate();bindShell();renderAll();const cam=state.data.settings.cameras?.[state.space];if(cam)state.camera=cam;else fitAll();applyCamera()}
function bindShell(){shell.querySelectorAll('[data-space]').forEach(b=>b.onclick=()=>{state.space=b.dataset.space;state.selectedId=null;state.actionsId=null;showShell()});shell.querySelector('#createBtn').onclick=()=>openPicker();shell.querySelectorAll('[data-create]').forEach(b=>b.onclick=()=>newNode(b.dataset.create));shell.querySelector('#fitBtn').onclick=fitAll;shell.querySelector('#focusBtn').onclick=()=>{state.camera.scale=1;state.camera.x=innerWidth/2-1800;state.camera.y=innerHeight/2-1300;applyCamera();save()};shell.querySelector('#zoomRange').oninput=e=>{state.camera.scale=Number(e.target.value);applyCamera()};shell.querySelector('#menuBtn').onclick=openMenu;shell.querySelector('#nowBtn').onclick=openNow;shell.querySelector('#archiveBtn').onclick=openArchive;shell.querySelector('#hintClose')?.addEventListener('click',()=>{state.data.settings.hintDismissed=true;document.querySelector('#hint').remove();save()});initCanvas({onChange:kind=>{if(kind==='links')renderLinks();else if(kind==='selection')syncSelection();else renderAll();save()},onOpen:id=>openDetail(id),onLong:id=>openEditor(id),onLink:id=>{startLink(id,toast);save()}});document.addEventListener('bw-save',save,{once:true})}
function renderAll(){const root=shell.querySelector('#nodes');root.innerHTML=state.data.nodes.filter(n=>n.space===state.space&&!n.archived).map(nodeHtml).join('');hydrateCovers(root);renderLinks();syncSelection();const n=node(state.actionsId);if(n)positionActions(n)}
function syncSelection(){shell.querySelectorAll('.node').forEach(el=>el.classList.toggle('selected',el.dataset.id===state.selectedId));const n=node(state.actionsId);if(n)positionActions(n);else hideActions()}
function node(id){return state.data.nodes.find(n=>n.id===id)}
function openDetail(id){const n=node(id);if(!n)return;if(state.linkSourceId){startLink(id,toast);save();renderLinks();return}state.detailId=id;const root=shell.querySelector('#modalRoot');root.innerHTML=detailHtml(n);hydrateCovers(root);bindModal(root,n)}
function openEditor(id){const n=node(id);if(!n)return;state.editId=id;const root=shell.querySelector('#modalRoot');root.innerHTML=editorHtml(n);hydrateCovers(root);bindEditor(root,n)}
function bindModal(root,n){root.querySelector('[data-close]').onclick=closeModal;root.querySelector('[data-close-modal]').onclick=e=>{if(e.target.dataset.closeModal!==undefined)closeModal()};root.querySelector('[data-edit-node]').onclick=()=>openEditor(n.id);root.querySelector('[data-archive-node]').onclick=()=>{n.archived=true;save();closeModal();renderAll()};root.querySelectorAll('[data-open-related]').forEach(b=>b.onclick=()=>openDetail(b.dataset.openRelated))}
function bindEditor(root,n){root.querySelector('[data-close]').onclick=closeModal;root.querySelector('[data-close-modal]').onclick=e=>{if(e.target.dataset.closeModal!==undefined)closeModal()};root.querySelector('[data-pick-media]').onclick=()=>{pendingMedia=n;document.querySelector('#mediaInput').click()};root.querySelector('[data-delete-node]').onclick=()=>{if(confirm('Удалить карточку?')){state.data.nodes=state.data.nodes.filter(x=>x.id!==n.id);state.data.links=state.data.links.filter(l=>l.from!==n.id&&l.to!==n.id);save();closeModal();renderAll()}};root.querySelector('#editForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);for(const [k,v] of f.entries())n[k]=['progress'].includes(k)?Number(v):v;save();closeModal();renderAll();toast('Сохранено')}}
function closeModal(){shell.querySelector('#modalRoot').innerHTML='';state.detailId=null;state.editId=null}
function openPicker(){const root=shell.querySelector('#modalRoot');root.innerHTML=createPicker();root.querySelector('[data-close]').onclick=closeModal;root.querySelector('[data-close-modal]').onclick=e=>{if(e.target.dataset.closeModal!==undefined)closeModal()};root.querySelectorAll('[data-new-type]').forEach(b=>b.onclick=()=>newNode(b.dataset.newType))}
function newNode(type){const c=screenCenter();const n={id:uid(),type,space:state.space,x:c.x,y:c.y,level:2,title:`Новый ${TYPE_LABELS[type].toLowerCase()}`,status:'active',assets:[],archived:false,locked:false};if(type==='process'){n.tasks=[];n.stages=[];n.progress=0}if(type==='person'){n.speciality='Специалист';n.personStatus='Новый контакт'}if(type==='goal')n.progress=0;state.data.nodes.push(n);save();closeModal();renderAll();openEditor(n.id)}
function screenCenter(){return{x:(innerWidth/2-state.camera.x)/state.camera.scale-145,y:(innerHeight/2-state.camera.y)/state.camera.scale-103}}
function fitAll(){const ns=state.data.nodes.filter(n=>n.space===state.space&&!n.archived);if(!ns.length){state.camera={x:innerWidth/2-1800,y:innerHeight/2-1300,scale:.75};applyCamera();return}const minX=Math.min(...ns.map(n=>n.x)),minY=Math.min(...ns.map(n=>n.y)),maxX=Math.max(...ns.map(n=>n.x+390)),maxY=Math.max(...ns.map(n=>n.y+280));const pad=120,scale=clamp(Math.min((innerWidth-pad)/(maxX-minX),(innerHeight-260)/(maxY-minY)),.35,1.2);state.camera.scale=scale;state.camera.x=(innerWidth-(maxX-minX)*scale)/2-minX*scale;state.camera.y=(innerHeight-(maxY-minY)*scale)/2-minY*scale;applyCamera();shell.querySelector('#zoomRange').value=scale;save()}
function save(){state.data.settings.cameras=state.data.settings.cameras||{};state.data.settings.cameras[state.space]=state.camera;store.save(state.userId,state.data)}
function openMenu(){const root=shell.querySelector('#modalRoot');root.innerHTML=`<div class="overlay" data-close-modal><section class="sheet" data-modal><header class="sheet-head"><div><small>BOONWAVE 7.0.0</small><h2>Меню</h2></div><button data-close>×</button></header><div class="sheet-body"><div class="click-list"><button class="click-row" id="exportBtn"><span class="click-icon">⇧</span><span><b>Экспорт данных</b><small>Резервная копия JSON</small></span><span>›</span></button><button class="click-row" id="importBtn"><span class="click-icon">⇩</span><span><b>Импорт данных</b><small>Восстановить резервную копию</small></span><span>›</span></button><button class="click-row" id="logoutBtn"><span class="click-icon">↪</span><span><b>Выйти</b><small>Локальный профиль</small></span><span>›</span></button></div></div></section></div>`;root.querySelector('[data-close]').onclick=closeModal;root.querySelector('[data-close-modal]').onclick=e=>{if(e.target.dataset.closeModal!==undefined)closeModal()};root.querySelector('#exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(store.exportData(state.data));a.download='boonwave-backup.json';a.click()};root.querySelector('#importBtn').onclick=()=>{const i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=async()=>{state.data=store.importData(await i.files[0].text());save();closeModal();showShell()};i.click()};root.querySelector('#logoutBtn').onclick=()=>{store.clearSession();location.reload()}}
function openNow(){const tasks=state.data.nodes.filter(n=>n.type==='process'&&!n.archived).flatMap(p=>(p.tasks||[]).filter(t=>!t.done).map(t=>({...t,processId:p.id,processTitle:p.title})));const root=shell.querySelector('#modalRoot');root.innerHTML=`<div class="overlay" data-close-modal><section class="sheet" data-modal><header class="sheet-head"><div><small>ФОКУС</small><h2>Я сейчас</h2></div><button data-close>×</button></header><div class="sheet-body"><div class="click-list">${tasks.length?tasks.map(t=>`<button class="click-row" data-open-process="${t.processId}"><span class="click-icon">✓</span><span><b>${t.title}</b><small>${t.processTitle}</small></span><span>›</span></button>`).join(''):'<div class="stat">Активных задач нет</div>'}</div></div></section></div>`;root.querySelector('[data-close]').onclick=closeModal;root.querySelectorAll('[data-open-process]').forEach(b=>b.onclick=()=>openDetail(b.dataset.openProcess))}
function openArchive(){const archived=state.data.nodes.filter(n=>n.archived);const root=shell.querySelector('#modalRoot');root.innerHTML=`<div class="overlay" data-close-modal><section class="sheet" data-modal><header class="sheet-head"><div><small>АРХИВ</small><h2>Карточки</h2></div><button data-close>×</button></header><div class="sheet-body"><div class="click-list">${archived.length?archived.map(n=>`<button class="click-row" data-restore="${n.id}"><span class="click-icon">↺</span><span><b>${n.title}</b><small>${TYPE_LABELS[n.type]}</small></span><span>Вернуть</span></button>`).join(''):'<div class="stat">Архив пуст</div>'}</div></div></section></div>`;root.querySelector('[data-close]').onclick=closeModal;root.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>{node(b.dataset.restore).archived=false;save();openArchive();renderAll()})}
document.querySelector('#mediaInput').onchange=async e=>{if(!pendingMedia||!e.target.files[0])return;const meta=await putFile(e.target.files[0]);pendingMedia.coverAssetId=meta.id;save();const img=document.querySelector('#mediaPreview img')||document.createElement('img');img.src=await getUrl(meta.id);document.querySelector('#mediaPreview').innerHTML='';document.querySelector('#mediaPreview').appendChild(img);e.target.value='';pendingMedia=null};
function toast(t){notice.textContent=t;notice.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>notice.classList.add('hidden'),1800)}
function demo(){const d=store.blank();const p=uid(),pr=uid(),pe=uid(),i=uid(),g=uid();d.nodes=[{id:p,type:'project',space:'work',x:1350,y:900,level:2,title:'Приложение',client:'ЛЮДИ ЗЕМЛИ',progress:40,positions:15},{id:pr,type:'process',space:'work',x:1730,y:1050,level:2,title:'Производство и монтаж',tasks:[{id:uid(),title:'Проверить интерфейс',done:false}],stages:[],progress:35},{id:pe,type:'person',space:'work',x:1580,y:700,level:2,title:'Алексей',speciality:'Творец',personStatus:'Работаем',phone:'+79000000000',telegram:'Avoblago'},{id:i,type:'idea',space:'work',x:1970,y:820,level:2,title:'Новая идея',source:'Pinterest'},{id:g,type:'goal',space:'work',x:1180,y:1180,level:2,title:'Новая цель дом-прицеп',metric:'15%',progress:15}];d.links=[{id:uid(),from:p,to:pr},{id:uid(),from:p,to:pe},{id:uid(),from:pe,to:i},{id:uid(),from:p,to:g}];return d}
